services:
  db:
    image: postgres:17
    container_name: food-postgres
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB=food
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - postgres_password
    networks:
    - app-network

secrets:
  postgres_password:
    file: ./database_password.txt

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    external: true
