services:
  web:
    container_name: fastapi-recipes-app
    image: fastapi-recipes:latest
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development